/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HurghadaRouteImport } from './routes/hurghada'
import { Route as MarsaAlamRouteImport } from './routes/marsa-alam'
import { Route as TourSlugRouteImport } from './routes/tour.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HurghadaRoute = HurghadaRouteImport.update({
  id: '/hurghada',
  path: '/hurghada',
  getParentRoute: () => rootRouteImport,
} as any)
const MarsaAlamRoute = MarsaAlamRouteImport.update({
  id: '/marsa-alam',
  path: '/marsa-alam',
  getParentRoute: () => rootRouteImport,
} as any)
const TourSlugRoute = TourSlugRouteImport.update({
  id: '/tour/$slug',
  path: '/tour/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/hurghada': typeof HurghadaRoute
  '/marsa-alam': typeof MarsaAlamRoute
  '/tour/$slug': typeof TourSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/hurghada': typeof HurghadaRoute
  '/marsa-alam': typeof MarsaAlamRoute
  '/tour/$slug': typeof TourSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/hurghada': typeof HurghadaRoute
  '/marsa-alam': typeof MarsaAlamRoute
  '/tour/$slug': typeof TourSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/about' | '/contact' | '/hurghada' | '/marsa-alam' | '/tour/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/contact' | '/hurghada' | '/marsa-alam' | '/tour/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/hurghada'
    | '/marsa-alam'
    | '/tour/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  HurghadaRoute: typeof HurghadaRoute
  MarsaAlamRoute: typeof MarsaAlamRoute
  TourSlugRoute: typeof TourSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hurghada': {
      id: '/hurghada'
      path: '/hurghada'
      fullPath: '/hurghada'
      preLoaderRoute: typeof HurghadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marsa-alam': {
      id: '/marsa-alam'
      path: '/marsa-alam'
      fullPath: '/marsa-alam'
      preLoaderRoute: typeof MarsaAlamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour/$slug': {
      id: '/tour/$slug'
      path: '/tour/$slug'
      fullPath: '/tour/$slug'
      preLoaderRoute: typeof TourSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  HurghadaRoute: HurghadaRoute,
  MarsaAlamRoute: MarsaAlamRoute,
  TourSlugRoute: TourSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
